CREATE TABLE TRANSAKTION_EINNAHME (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TRANSAKTIONS_ART VARCHAR(255),
    JAHR_TRANSAKTION VARCHAR(255),
    MONAT_TRANSAKTION VARCHAR(255),
    HOEHE VARCHAR(255),
    WAEHRUNG VARCHAR(255)
);


CREATE TABLE TRANSAKTION_AUSGABE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TRANSAKTIONS_ART VARCHAR(255),
    KATEGORIE VARCHAR(255),
    BENUTZERDEFINIERTE_KATEGORIE VARCHAR(255),
    HOEHE VARCHAR(255),
    WAEHRUNG VARCHAR(255),
    DATUM_TRANSAKTION VARCHAR(10),
    TAG_TRANSAKTION VARCHAR(2),
    JAHR_TRANSAKTION VARCHAR(4),
    MONAT_TRANSAKTION VARCHAR(2)
);
