CREATE TABLE IF NOT EXISTS TRANSAKTION_EINNAHME (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TRANSAKTIONS_ART VARCHAR(255),
    JAHR_TRANSAKTION VARCHAR(255),
    MONAT_TRANSAKTION VARCHAR(255),
    HOEHE VARCHAR(255),
    WAEHRUNG VARCHAR(255)
);


CREATE TABLE IF NOT EXISTS TRANSAKTION_AUSGABE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TRANSAKTIONS_ART VARCHAR(255),
    KATEGORIE VARCHAR(255),
    BENUTZERDEFINIERTE_KATEGORIE VARCHAR(255),
    HOEHE VARCHAR(255),
    WAEHRUNG VARCHAR(255),
    DATUM_TRANSAKTION VARCHAR(10),
    TAG_TRANSAKTION VARCHAR(2),
    JAHR_TRANSAKTION VARCHAR(4),
    MONAT_TRANSAKTION VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS TRANSAKTION_NOTIZ (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TRANSAKTIONS_ART VARCHAR(255),
    JAHR_TRANSAKTION VARCHAR(4),
    MONAT_TRANSAKTION VARCHAR(255),
    NOTIZ VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS TRANSAKTION_UEBERSICHT (
    ID BEGINT AUTO_INCREMENT PRIMARY KEY,

)
