CREATE TABLE IF NOT EXISTS TRANSAKTION_EINNAHME (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TRANSAKTIONS_ART VARCHAR(255),
    JAHR_TRANSAKTION VARCHAR(255),
    MONAT_TRANSAKTION VARCHAR(255),
    HOEHE VARCHAR(255),
    WAEHRUNG VARCHAR(255)
);


CREATE TABLE IF NOT EXISTS TRANSAKTION_AUSGABE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TRANSAKTIONS_ART VARCHAR(255),
    KATEGORIE VARCHAR(255),
    BENUTZERDEFINIERTE_KATEGORIE VARCHAR(255),
    HOEHE VARCHAR(255),
    WAEHRUNG VARCHAR(255),
    JAHR_TRANSAKTION VARCHAR(4),
    MONAT_TRANSAKTION VARCHAR(255),
    IST_SCHULDEN BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS TRANSAKTION_NOTIZ (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TRANSAKTIONS_ART VARCHAR(255),
    JAHR_TRANSAKTION VARCHAR(4),
    MONAT_TRANSAKTION VARCHAR(255),
    NOTIZ VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS SCHULDEN (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SCHULDEN_BEZEICHNUNG VARCHAR(255),
    HOEHE VARCHAR(255),
    WAEHRUNG VARCHAR(255)
);
